"metadata";
import { Inter } from "next/font/google";
import "./globals.css";
import MyGlobalState from "@/Context/Context";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Deep-Pexels",
  description: "Generated by Deep-Pexels",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyGlobalState>
          <Header />
          {children}
        </MyGlobalState>
      </body>
    </html>
  );
}
